server:
# TODO: Disabled https because is necessary to configure client into tests
#  port: 8443
#  ssl:
#    key-store: demo-contactapi-keystore.p12
#    key-store-password: ${DEMO_CONTACTAPI_KEYSTORE_PASSWORD}
#    key-store-type: PKCS12
#    key-alias: democontactapi
  servlet:
    context-path: /api

spring:
  application:
    name: demo.contactapi
  datasource:
    target: ${DATA_SOURCE_TARGET:static}
    h2:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password:
    postgres:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/mydatabase
      username: postgres
      password: mysecretpassword
    jpa:
      hibernate:
        ddl-auto: create-drop
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
